'use strict';

/**
 * Build `main.js` — the single file Obsidian actually installs.
 *
 * ## Why a build step exists
 *
 * Obsidian only downloads three files from a release: `main.js`, `manifest.json` and
 * `styles.css`. A plugin that does `require('./study-profile.js')` at load time therefore
 * **crashes for every user installing it from the community directory**, even though it
 * works fine in a dev vault where the sibling file happens to sit next to `main.js`.
 *
 * So the shipped `main.js` is a real bundle. To keep it honest and reviewable:
 *
 *   - no bundler is used (no webpack/rollup) and there are still zero dependencies;
 *   - the only transformation is inlining `src/study-profile.js` inside an IIFE;
 *   - the source files stay separate and readable, and `main.js` is generated from them;
 *   - `dev/test.js` runs against the **built** `main.js`, so the artifact that ships is
 *     the artifact under test.
 *
 * The IIFE also solves scope collisions: both files declare `fs`, `path` and `os`, which
 * would be a redeclaration error if concatenated naively.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'src');
const MAIN_SRC = path.join(SRC, 'main.js');
const PROFILE_SRC = path.join(SRC, 'study-profile.js');
const OUT = path.join(ROOT, 'main.js');

const REQUIRE_LINE = "require('./study-profile.js')";
const BUNDLE_MARKER = '/* ==== bundled module: study-profile.js ==== */';

/** Turn the CommonJS module into an IIFE that evaluates to its exports object. */
function wrapAsIife(source, relPath) {
  let body = source;

  // Drop the module's own `'use strict'`; the wrapper establishes it.
  body = body.replace(/^\s*'use strict';\s*\n/, '');

  // CommonJS export -> IIFE return value.
  const exportRe = /^module\.exports\s*=\s*\{/m;
  if (!exportRe.test(body)) {
    throw new Error(`${relPath}: expected a top-level "module.exports = {" block to convert`);
  }
  body = body.replace(exportRe, 'return {');

  // Guard against any other module-level CommonJS syntax silently surviving.
  if (/^\s*module\.exports/m.test(body)) {
    throw new Error(`${relPath}: found an unexpected second module.exports`);
  }

  return [
    BUNDLE_MARKER,
    `// Inlined from ${relPath} by dev/build.js — edit the source file, not this copy.`,
    'const studyProfile = (function () {',
    "'use strict';",
    body.replace(/\s*$/, ''),
    '})();',
  ].join('\n');
}

/** Build in memory and return the exact text that would be written. */
function render() {
  const main = fs.readFileSync(MAIN_SRC, 'utf8');
  const profile = fs.readFileSync(PROFILE_SRC, 'utf8');

  const occurrences = main.split(REQUIRE_LINE).length - 1;
  if (occurrences !== 1) {
    throw new Error(`expected exactly one "${REQUIRE_LINE}" reference in src/main.js, found ${occurrences}`);
  }

  const banner = [
    '/* eslint-disable */',
    '/*',
    ' * Pion — generated bundle. DO NOT EDIT THIS FILE DIRECTLY.',
    ' *',
    ' * Source of truth: src/main.js and src/study-profile.js',
    ' * Regenerate with: npm run build',
    ' *',
    ' * Obsidian installs only main.js + manifest.json + styles.css from a release, and this',
    ' * file is loaded by Obsidian itself (it is not a module), so it must be self-contained.',
    ' */',
  ].join('\n');

  const assignRe = /^[ \t]*const studyProfile = require\('\.\/study-profile\.js'\);.*$/m;
  if (!assignRe.test(main)) {
    throw new Error('could not find the study-profile assignment line in src/main.js');
  }

  const iife = wrapAsIife(profile, 'src/study-profile.js');
  let out = main.replace(assignRe, iife);

  if (!out.includes(BUNDLE_MARKER)) throw new Error('bundle marker missing — inlining did not happen');
  if (/require\('\.\/study-profile\.js'\)/.test(out)) throw new Error('bundle still requires study-profile.js at runtime');

  out = out.replace(/^\s*'use strict';\s*\n/, '');
  return `${banner}\n'use strict';\n\n${out.replace(/^\s+/, '')}`;
}

function build() {
  for (const f of [MAIN_SRC, PROFILE_SRC]) {
    if (!fs.existsSync(f)) throw new Error(`missing source file: ${f}`);
  }
  const final = render();
  fs.writeFileSync(OUT, final, 'utf8');
  return { bytes: fs.statSync(OUT).size, lines: final.split('\n').length };
}

/** Fail if the committed bundle is out of date with src/ (used by CI). */
function checkUpToDate() {
  for (const f of [MAIN_SRC, PROFILE_SRC]) {
    if (!fs.existsSync(f)) throw new Error(`missing source file: ${f}`);
  }
  const expected = render();
  const actual = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
  if (actual === null) {
    throw new Error('main.js is missing — run `npm run build`');
  }
  if (actual !== expected) {
    throw new Error('main.js is out of date with src/ — run `npm run build` and commit the result');
  }
  return { bytes: Buffer.byteLength(expected, 'utf8'), lines: expected.split('\n').length };
}

if (require.main === module) {
  const upToDate = process.argv.includes('--check');
  try {
    if (upToDate) {
      const r = checkUpToDate();
      console.log(`main.js is up to date with src/ — ${r.lines} lines, ${(r.bytes / 1024).toFixed(1)} KB`);
    } else {
      const r = build();
      console.log(`built main.js — ${r.lines} lines, ${(r.bytes / 1024).toFixed(1)} KB`);
    }
  } catch (e) {
    console.error('build check failed: ' + e.message);
    process.exit(1);
  }
}

module.exports = { build, render, checkUpToDate };
